development:
  adapter: postgresql
  encoding: utf8
  database: c9
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['IP'] %>
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: c9_test
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['IP'] %>
  template: template0