# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d218f4b6f7015ff61afc9d5892f4e76301c931310d7b0e0946b391a973de3bf7b3c48c65346311e38c284b58bd07a4117e9ba46cd3099e8f0810ff1bfa0038e

test:
  secret_key_base: 894feec8ec41e52064f7d2f7ec249e6144ae2bbe891f568d80414ace5db9a8b68d89f6003af47b907fcf178ac04d6dbcc05c7aa28ce963cd8e941a500cc08570

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
